# Generated by Django 5.0 on 2023-12-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Restaurant',
        ),
    ]
